version: 2
jobs:
  build:
    working_directory: ~/demo
    docker:
      - image: circleci/ruby:2.6.5-node
        environment:
          PGHOST: localhost
          PGUSER: demo
          RAILS_ENV: test
          SELENIUM_DRIVER_URL: http://localhost:4444/wd/hub
      - image: circleci/postgres:9.6.3-alpine
        environment:
          POSTGRES_USER: demo
          POSTGRES_DB: demo_test
          POSTGRES_PASSWORD: ""
      - image: selenium/standalone-chrome:3.4.0
    steps:
      - checkout

      # Restore Cached Dependencies
      - type: cache-restore
        name: Restore bundle cache
        key: demo-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      - run: npm install

      # Cache Dependencies
      - type: cache-save
        name: Store bundle cache
        key: demo-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      # Wait for DB
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m

      # Setup the environment
      # - run: cp .sample.env .env

      # Setup the database
      - run: bundle exec rake db:setup

      # Database setup
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load

      - run: bundle exec rake

      # Save artifacts
      - type: store_test_results
        path: /tmp/test-results
